# 오류 코드를 예외로 바꾸기

> 예외는 프로그래밍 언어에서 제공하는 독립적인 오류 처리 메커니즘이다. 오류가 발견되면 예외를 던진다. 그러면 적절한 예외 핸들러를 찾을 때까지 콜스택을 타고 위로 전파된다. 예외를 사용하면 오류 코드를 일일이 검사하거나 오류를 식별해 콜스택 위로 던지는 일을 신경쓰지 않아도 된다.

> 예외에는 독자적인 흐름이 있어서 프로그램의 나머지에서는 오류 발생에 따른 복잡한 상황에 대처하는 코드를 작성하거나 읽을 일이 없게 해준다.

> 예외를 던지는 코드를 프로그램 종료 코드로 바꿔도 프로그램이 여전히 정상 동작할지를 따져봐서 정상 동작하지 않을것 같다면 예외를 사용하지 말라는 신호, 예외 대신 오류를 검출하여 프로그램을 정상 흐름으로 되돌리게끔 처리해야 한다.

ex:)

```js
if (data) return new ShippingRules(data);
else return -23;

//Refactoring
if (data) return new ShippingRules(data);
else throw new OrderProcessingError(-23);
```

### 절차

1. 콜스택 상위에 해당 예외를 처리할 예외 핸들러를 작성
   - 이 핸들러는 처음에는 모든 예외를 다시 던지게 해둔다.
   - 적절한 처리를 해주는 핸들러가 이미 있다면 지금의 콜스택도 처리할 수 있도록 확장
2. 테스트
3. 해당 오류 코드를 대체할 예외와 그 밖의 예외를 구분할 식별 방법을 찾는다.
   - 사용하는 프로그래밍 언어에 맞게 선택하면 된다. 대부분 언어에서는 서브클래스를 사용하면 될 것
4. 정적 검사 수행
5. catch절을 수정하여 직접 처리할 수 있는 예외는 적절히 대처하고 그렇지 않은 예외는 다시 던진다.
6. 테스트
7. 오류 코드를 반환하는 곳 모두에서 예외를 던지도록 수정한다.
8. 모두 수정했다면 그 오류 코드를 콜스택 위로 전달하는 코드를 모두 제거한다.
   - 먼저 오류 코드를 검사하는 부분을 함정으로 바꾼 다음, 함정에 걸려들지 않는지 테스트 한 후 제거하는 전략을 권한다.

### 예시

```js
전역 테이블에서 배송지의 배송 규칙을 알아내는 코드
function localShippingRules(country) {
    const data = countryData.shippingRules[country];
    if (data) return new ShippingRules(data);
    else return -23;
}

function calculateShippingCosts(anOrder) {
    //관련없는 코드
    const shippingRules = localShippingRules(anOrder.country);
    if(shippingRuls < 0) return shippingRules; //오류 전파
    //더 관련 없는 코드
}
더 윗단 함수는 오류를 낸 주문을 오류 목록(errorList)에 넣는다.
//최상위
const status = calculateShippingCosts(orderData);
if(status < 0) errorList.push({order: orderData, errorCode: status});

여기서 가장 먼저 고려할 것은 이 오류가 '예상된 것이냐'이다.
예상할 수 있는 정상 동작 범주에 든다면 오류 코드를 예외로 바꾸는 이번 리팩터링을 적용할 준비가 된것이다.

1. 가장 먼저 최상위에 예외 핸들러를 갖춘다. localShippingRules()을 호출을 try 블록으로 감싸려하지만 처리 로직은 포함하고 싶지 않다. 그런데 다음처럼 할수는 없다.
//최상위
try {
    const status = calculateShippingCosts(orderData);
} catch(e) {
    //예외처리 로직
}
if(status <0) errorList.push({order:orderData, errorCode: status});

이렇게 하면 status의 유효범위가 try블록으로 국한되어 조건문에서 검사할수 없다.
그래서 status 선언과 초기화를 분리해야 한다.
//최상위
let status;
status = calculateShippingCosts(orderData);
if (status < 0) errorList.push({order: orderDatam, errorCode: status});
이제 함수 호출을 try/catch 블록으로 감쌀수 있다.

//최상위
let satatus;
try {
    status = calculateShippingCosts(orderData);
} catch(e) {
    throw e;
}
if (status < 0) errorList.push({order: orderDatam, errorCode: status});

3. 이번 리패터링으로 추가된 예외만을 처리하고자 한다면 다른 예외와 구별할 방법이 필요하다. 별도의 클래스를 만들어서 할수도 있고 특별한 값을 부여하는 방법도 있다. (현재)자스는 여기해당되지 않지만 다음 처럼하는걸 좋아함

class orderProcessingError exnteds Error {
    constructor(errorCode) {
        super(`주문 처리 오류 ${errorCode}`);
        this.code = errorCode;
    }
    get name() {return 'OrderProcessingError';}
}

5. 이 클래스가 준비되면 오류 코드를 처리할 때와 같은 방식으로 이 예외 클래스를 처리하는 로직을 추가할 수 있다.

//최상위
let status;
try {
    status = calculateShippingCosts(orderData);
} catch(e) {
    if(e instanceof OrderProcessingError)
        errorList.push({order: orderData, errorCode: e.code});
    else
        throw e;
}
if (status < 0) errorList.push({order: orderData, errorCode: status});

7. 그런 다음 오류 검출 코드를 수정하여 오류 코드 대신 이 예외를 던지도록 한다.

function localShippingRules(country) {
    const data = countryData.shippingRules[country];
    if (data) return new ShippingRules(data);
    else throw new OrderProcessingError(-23);
}

8. 코드를 다 작성했고 테스트도 통과했다면 오류 코드를 전파하는 임시 코드를 제거할 수 있다. 하지만 나라면 먼저 다음으로 함정을 추가한 후 테스트해볼 것
function calculateShippingCosts(anOrder) {
    //관련없는 코드
    const shippingRules = localShippingRules(anOrder.country);
    if(shippingRules < 0) throw new Error('오류 코드가 다 사라지지 않았다.');
    //더 관련없는 코드
}

이 함정에 걸려들지 않는다면 이 줄 전체를 제거해도 안전하다. 오류를 콜스택 위로 전달하는 일은 예외 메커니즘이 대신 처리해 줄것이기 때문

function calculateShippingCosts(anOrder) {
    //관련없는 코드
    const shippingRules = localShippingRules(anOrder.country);
    //더 관련없는 코드
}

//최상위
let status;
try {
    status = calculateShippingCosts(orderData);
} catch(e) {
    if(e instanceof OrderProcessingError)
        errorList.push({order: orderData, errorCode: e.code});
    else
        throw e;
}

이제는 필요 없어진 status 변수 역시 제거할 수 있다.
try {
    calculateShippingCosts(orderData);
} catch(e) {
    if(e instanceof OrderProcessingError)
        errorList.push({order: orderData, errorCode: e.code});
    else
        throw e;
}
```
