## 비동기적 프로그래밍

> 자바스크립트 애플리케이션은 단일 스레드에서 동작한다. 즉, 자바스크립트는 한번에 한가지 일만 할 수 있다.

- 자바스크립트의 비동기적 프로그래밍의 3가지 패러다임

  1. 콜백

  - 제너레이터나 프라미스 외에도 이벤트 처리 등에 유용하게 씀

  2. 프로미스

  - 콜백에 의존

  3. 제너레이터

  - 제너레이터 자체는 비동기적 프로그래밍을 전혀 지원하지 않음
  - 프라미스나 특수한 콜백과 함꼐 사용해야 비동기적 사용가능

- 사용자 입력 외에, 비동기적 테크닉을 사용해야 하는 경우 3가지
  1. Ajax 호출을 비롯한 네트워크 요청
  2. 파일을 읽고 쓰는 등의 파일시스템 작업
  3. 의도적으로 시간 지연을 사용하는 기능(알람 등)

#### 요약

- 자바스크립트의 비동기적 실행은 콜백을 통해 이루어짐
- 프로미스를 콜백 대신 사용할 수 있는 건아니다. 프로미스 역시 콜백을 사용
- 프로미스는 콜백이 여러번 호출되는 문제를 해결
- 프로미스는 반드시 결정된다는(성공 또는 실패한다는) 보장은 없다.
  - 프로미스에 타임아웃을 걸면 이 문제가 해결됨
- 프로미스는 체인으로 연결할 수 있다.
-

### 콜백

> 콜백은 자바스크립트에서 가장 오래된 비동기적 메커니즘
> <br> 콜백은 간단히 말해 나중에 호출할 함수이다.

- 콜백 함수 자체에는 특별할 것이 전혀 없다.
  - 일반적인 자바스크립트 함수일 뿐
- 콜백 함수는 일반적으로 다른 함수에 넘기거나 객체의 프로퍼티로 사용한다.
- 콜백은 보통 익명 함수로 사용한다.

- 비동기적 실행의 가장 큰 목적, 가장 중요한 요점은 어떤 것도 차단하지 않는다는 것

#### setInterval과 clearInterval

> setTimeout은 콜백 함수를 한 번만 실행하고 멈추지만, setInterval은 콜백을 정해진 주기마다 호출하며 clearInterval을 사용할 떄까지 멈추지 않는다.

- ```js
  const start = new Date();
  let i = 0;
  const intervalId = setInterval(function () {
    let now = new Date();
    if (now.getMinutes() !== start.getMinutes() || ++i > 10) return clearInterval(intervalId);
    //clearInterval은 setInterval이 반환하는 ID를 받아 타임아웃을 멈춘다.
    console.log(`${i}: ${now}`);
  }, 5 * 1000);
  ```

- setTimeout, setInterval, clearInterval은 모두 전역 객체(브라우저에서는 window, 노드에서는 global)에 정의되어 있다.

#### 스코프와 비동기적 실행

> 비동기적 실행에서 혼란스럽고 에러도 자주 일어나는 부분은 스코프와 클로저가 비동기적 실행에 영향을 미치는 부분이다.

- 함수를 호출하면 항상 클로저가 만들어진다.

  - 매개변수를 포함해 함수 안에서 만든 변수는 모두 무언가가 자신에 접근할 수 있는 한 계속 존재한다.

- ```js
  function countdown() {
    let i; // i를 for 루프 밖에서 선언함
    console.log("CountDown:");
    for (i = 5; i >= 0; i--) {
      //setTimeout을 호출하는것 역시 동기적
      setTimeout(function () {
        //비동기적인 부분은 setTimeout에 전달된 함수
        console.log(i === 0 ? "GO!" : i);
      }, (5 - i) * 1000); //동기적으로 실행됬기에 예상되로 순서대로 작동함
    }
  }
  //for 루프가 실행을 마치고 i의 값이 -1이 된다음에서야 콜백이 실행됨
  //문제는 콜백이 실행될 때 i의 값은 이미 -1

  countdown();
  //countdown을 호출하면 변수 i가 들어있는 클로저가 만들어짐
  //for 루프안에서 만드는 콜백은 모두 i에 접근 할 수 있고, 그들이 접근하는 i는 똑같은 i
  ```

- ```js
  function countdown() {
    console.log("Countdown:");
    for (let i = 5; i >= 0; i--) {
      //이제 i는 블록 스코프 변수
      setTimeout(function () {
        //※주의할점: 콜백이 어느 스코프에서 선언됐느냐
        //콜백은 자신을 선언한 스코프(클로저)에 있는 것을 접근할 수 있다.
        //따라서 i의 값은 콜백이 실제 실행되는 순간마다 다를 수 있다.
        console.log(i === 0 ? "GO!" : i);
      }, (5 - i) * 1000);
    }
  }

  countdown();
  ```

### 오류 우선 콜백

> 콜백을 사용하면 예외 처리가 어려워지므로, 콜백과 관련된 에러를 처리할 방법의 표준이 필요했음
> <br>이에 따라 나타난 패턴이 콜백의 첫번째 매개변수에 에러 객체를 쓰자는 것 (에러가 null이나 undefined이면 에러가 없는 것)

- ```js
  const fs = require("fs");

  const fname = "may_or_may_not_exist.txt";
  fs.readFile(fname, function (err, data) {
    if (err) return console.error(`error reading file ${fname}: ${err.message}`);
    console.log(`${fname} contents: ${data}`);
  });

  //콜백에서 가장 먼저 하는일은 err이 참같은 값인지 확인하는 것
  //err이 참같은 값이면 파일을 읽는데 문제가 있다는 뜻이므로 콘솔에 오류를 보고하고 즉시 빠져나옴
  ```

- 오류 우선 콜백을 사용할 때 가장 많이 벌어지는 실수
  - 에러 객체를 체크해야 한다는 사실을 기억하고, 아마 로그를 남기기도 하겠지만, 빠져나와야 한다는 사실은 잊는 사람이 많다.
  - 콜백함수는 대게 콜백이 성공적이라고 가정하고 만들어진다.
  - 그런데 콜백이 실패했으니 빠져나가지 않으면 오류를 예약하는 것이나 다름없다.
- 프로미스를 사용하지 않으면 오류 우선 콜백은 노드 개발의 표준이나 다름없다.
  - 콜백을 사용하는 인터페이스를 만들 때는 오류 우선 콜백을 사용하자

### 콜백지옥

> 한번에 여러가지를 기다려야 한다면 콜백을 관리하기가 상당히 어려워진다.

- ```js
  // 세가지 파일의 콘텐츠를 읽고, 60초가 지난 다음 이들을 결합해 네 번째 파일에 기록한다.
  const fs = require("fs");

  fs.readFile("a.text", function (err, dataA) {
    if (err) console.error(err);
    fs.readFile("b.text", function (err, dataB) {
      if (err) console.error(err);
      fs.readFile("c.text", function (err, dataC) {
        if (err) console.error(err);
        setTimeout(function () {
          fs.writeFile("d.text", dataA + dataB + dataC, function (err) {
            if (err) console.error(err);
          });
        }, 60 * 1000);
      });
    });
  });
  ```

### 프로미스

> 프로미스는 콜백의 단점을 해결하려는 시도 속에서 만들어 졌다. <br>프로미스는 간혹 번거롭게 느껴질수 있지만, 일반적으로 안전하고 관리하기 쉬운 코드를 만들 수 있게 한다.

- 프로미스가 콜백을 대체하는 것은 아님

  - 프로미스에서도 콜백을 사용함
  - 프로미스는 콜백을 예측 가능한 패턴으로 사용할 수 있게 함
  - 프라미스 없이 콜백만 사용했을 때 나타날 수 있는 엉뚱한 현상이나 찾기 힘든 버그를 상당수 해결함

- 프로미스의 기본 개념은 간단하다

  - 프로미스 기반 비동기적 함수를 호출하면 그 함수는 Promise 인스턴스를 반환한다.
  - 프라미스는 성공(fulfilled)하거나, 실패(rejected)하거나 단 두가지 뿐
  - 성공이든 실패든 단 한번만 일어난다.
  - 프라미스가 성공하거나 실패하면 그 프라미스르 결정됐다고 한다.

- 프로미스는 객체이므로 어디든 전달할 수 있다는 점도 콜백에 비해 간편한 장점이다.
  - 비동기적 처리를 여기서 하지 않고 다른 함수에서(또는 다른 동료가) 처리하게 하고 싶다면 프라미스를 넘기기만 하면 된다.
    - 마치 음식점에서 받은 예약 호출기를 친구에게 맡기는 것과 비슷하다
    - 예약한 인원이 때맞춰 오기만 한다면, 음식점에서는 누가 호출기를 들고 있든 상관없으니..

#### 프로미스 만들기

> resolve(성공)와 reject(실패) 콜백이 있는 함수로 새 Promise 인스턴스를 만들기만 하면된다.

- ```js
  function countdown(seconds) {
    return new Promise(function (resolve, reject) {
      for (let i = seconds; i >= 0; i--) {
        setTimeout(function () {
          if (i > 0) console.log(i + "...");
          else resolve(console.log("GO!")); //카운트다운이 끝나면 프로미스를 반환
        }, (seconds - i) * 1000);
      }
    });
  }
  ```
- resolve와 reject는 함수이다.
  - resolve나 reject를 여러번 호출하든, 섞어서 호출하든 결과는 같다.
  - 첫번째 호출한것만 의미가 있음
  - 프라미스는 성공 또는 실패를 나타낼 뿐

#### 프로미스 사용

- ```js
  //이 예제는 반환된 프라미스를 변수에 할당하지 않고 then 핸들러를 바로 호출함
  countdown(5).then(
    //then 핸들러는 성공 콜백과 에러 콜백을 받는다.
    function () {
      console.log("countdown completed successfully");
    },
    function (err) {
      console.log("countdown experienced an error: " + err.message);
    }
  );

  //프로미스는 catch 핸들러도 지원하므로 핸들러를 둘로 나눠서 써도 된다.
  const p = countdown(5);
  p.then(function () {
    console.log("countdown completed successfully");
  });
  p.catch(function (err) {
    console.log("countdown exprienced an error: " + err.message);
  });
  ```

- ```js
  function countdown(seconds) {
    return new Promise(function (resolve, reject) {
      for (let i = seconds; i >= 0; i--) {
        setTimeout(function () {
          if (i === 13) return reject(new Error("Oh my god"));
          //13이상의 숫자를 사용하면 에러가 일어남
          //하지만 콘솔에는 12부터 다시 카운트를 기록함
          // reject나 resolve가 함수를 멈추지는 않는다.
          // 이들은 그저 프로미스의 상태를 관리할 뿐
          if (i > 0) console.log(i + "...");
          else resolve(console.log("GO!"));
        }, (seconds - i) * 1000);
      }
    });
  }
  ```
- 프로미스는 비동기적 작업이 성공 또는 실패하도록 확정하는, 매우 안전하고 잘 정의된 메커니즘을 제공하지만<br>현재는 진행 상황을 전혀 알려주지 않는다.
  - 즉 프로미스는 완료되거나 파기될 뿐, '50% 진행됐다'라는 개념은 아예 없는 것

### 이벤트

> 이벤트가 일어나면 이벤트 발생을 담당하는 개체에서 이벤트가 일어났음을 알린다.

- 필요한 이벤트는 모두 주시(listen) 할 수 있다. (콜백을 통해서)
- 노드에는 이미 이벤트를 지원하는 모듈 EventEmiiter가 내장돼 있다.

- ```js
  // EventEmitter는 countdown같은 함수와 함꼐 사용해도 되지만, 원래는 클래스와 함께 사용하도록 설계됨
  const EvenEmitter = require("events").EventEmitter;
  //EventEmiiter를 상속하는 클래스는 이벤트를 발생시킬 수 있다.
  class Countdown extends EvenEmitter {
    constructor(seconds, superstitious) {
      super();
      this.seconds = seconds;
      this.superstitious = !!superstitious;
    }
    go() {
      const countdown = this;
      return new Promise(function(resolve, reject) {
        for(let i=countdown.seconds; i>=0; i--) {
          setTimeout(function() {
            if(countdown.superstitious && i === 13)
              return reject(new Error("oh my God"));
            countdown.emit('tick', i);//이 부분에서 tick 이벤트를 발생시키고,
            //필요하다면 프로그램의 다른 부분에서 이 이벤트를 주시할수 있다.
            if(i===0) resolve();
          }, (countdown.seconds-i)*1000);
        }
      });

  const c = new Countdown(5);

  c.on('tick', function(i) {//이벤트를 주시하는 부분
    if(i>0) console.log(i + "...");
  });
  c.go()
    .then(function() {
      console.log("GO!");
    })
    .catch(function(err) {
      console.error(err.message);
    })
  ```

- ```js
  const c = new Countdow(15, true).on("tick", function (i) {
    if (i > 0) console.log(i + "...");
  });

  c.go()
    .then(function () {
      console.log("GO!");
    })
    .catch(function (err) {
      console.error(err.message);
    });
  //여전히 프라미스를 파기헀는데도 카운트다운이 계속 진행됨
  //이 문제를 해결하려면 더 진행할 수 없다는 사실을 아는 즉시 대기중인 타임아웃을 모두 취소하면 된다.

  const EventEmitter = require("events").EventEmitter;

  class Countdown extends EventEmitter {
    constructor(seconds, superstitious) {
      super();
      this.secodns = secodns;
      this.superstitious = superstitious;
    }

    go() {
      const countdown = this;
      const timeoutIds = [];
      return new Promise(function (resolve, reject) {
        for (let i = countdown.seconds; i >= 0; i--) {
          timeoutIds.push(
            setTimeout(function () {
              if (countdown.superstitious && i === 13) {
                // 대기중인 타임아웃을 모두 취소한다.
                timeoutIds.forEach(clearTimeout);
                return reject(new Error("oh my god"));
              }
              countdown.emit("tick", i);
              if (i === 0) resolve();
            }, (countdown.second - i) * 1000)
          );
        }
      });
    }
  }
  ```

### 프로미스 체인

> 프로미스에는 체인으로 연결할 수 있다는 장점이 있다.
> <br> 즉, 프로미스가 완료되면 다른 프로미스를 반환하는 함수를 즉시 호출할 수 있다.

- ```js
  function launch() {
    return new Promise(function (resolve, reject) {
      console.log("Lift off!");
      setTimeout(function () {
        resolve("In orbit!");
      }, 2 * 1000);
    });
  }

  const c = new Countdown(5).on("tick", (i) => console.log(i + "..."));

  c.go()
    .then(launch)
    .then(function (msg) {
      console.log(msg);
    })
    .catch(function (err) {
      console.error("Houston, we have a problem...");
    });
  ```

- 프로미스 체인을 사용하면 모든 단계에서 에러를 캐치할 필요가 없다.
  - 체인 어디서든 에러가 생기면 체인 전체가 멈추고 catch 핸들러가 동작한다.

### 결정되지 않는 프라미스 방지하기

> 프로미스는 비동기적 코드를 단순화하고 콜백이 두 번 이상 실행되는 문제를 방지한다.
> <br>하지만 resolve나 reject를 호출하는 걸 잊어서 프로미스가 결정되지 않는 문제까지 자동으로 해결하지는 못한다.

- 결정되지 않은 프라미스를 방지하는 한 가지 방법은 프로미스에 타임아웃을 거는 것

  - 충분한 시간이 지났는데도 프라미스가 결정되지 않으면 자동으로 실패하게 만들 수 있다.
  - 물론 얼마나 기다려야 '충분히' 기다렸는지는 스스로 판단해야 한다.

- ```js
  function addTimeout(fn, timeout) {
    if (timeout === undefined) timeout = 1000; //타임아웃 기본값
    return function (...args) {
      return new Promise(function (resolve, reject) {
        const tid = setTimeout(reject, timeout, new Error("promise timed out"));
        fn(...args)
          .then(function (...args) {
            clearTimeout(tid);
            resolve(...args);
          })
          .catch(function (...args) {
            clearTimeout(tid);
            reject(...args);
          });
      });
    };
  }

  c.go()
    .then(addTimeout(launch, 11 * 1000))
    .then(function (msg) {
      console.log(msg);
    })
    .catch(function (err) {
      console.err(err.message);
    });
  ```

### 제너레이터

> 제너레이터는 원래 동기적인 성격을 가졌지만, 프로미스와 결합하면 비동기 코드를 효율적으로 관리할 수 있다.<br> **ES7에서 async await이 나왔다!!!**

- 제너레이터 실행기를 직접 만들진 말자

- ```js
  // 제너레이터를 사용하기 전 선행작업
  //1. 노드의 오류 우선 콜백을 프로미스로 바꾸는 것
  function nfcall(f, ...args) {
    return new Promise(function (resolve, reject) {
      f.call(null, ...args, function (err, ...args) {
        if (err) return reject(err);
        resolve(args.length < 2 ? args[0] : args);
      });
    });
  }

  //이제 콜백을 받는 노드 스타일 메서드를 모두 프로미스로 바꿀 수 있다.
  //setTimeout을 써야 하는데, setTimeout은 노드보다 먼저 나왔고 오류 우선 콜백의 패턴을 따르지 않는다.
  //그러니 같은 기능을 가진 ptimeout(promise timeout) 함수를 새로 만든다.

  function ptimeout(delay) {
    return new Promise(function (resolve, reject) {
      setTimeout(resolve, delay);
    });
  }

  //다음에 필요한 것은 제너레이터 실행기
  //제너레이터는 원래 동기적이다.
  /*하지만 제너레이터는 호출자와 통신할 수 있으므로 제너레이터와의 통신을 관리하고
    비동기적 호출을 처리하는 함수를 만들 수 있다.*/

  function grun(g) {
    const it = g();
    (function iterate(val) {
      if (!x.done) {
        if (x.value instanceof Promise) {
          x.value.then(iterate).catch((err) => it.throw(err));
        } else {
          setTimeout(iterate, 0, x.value);
        }
      }
    })();
  }
  //grun은 기초적인 제너레이터 재귀 실행기이다.
  //grun에 제너레이터 함수를 넘기면 해당 함수가 실행된다.
  //yield로 값을 넘긴 제너레이터는 이터레이터에서 next를 호출할 때 까지 기다린다.
  //grun은 그 과정을 재귀적으로 반복

  function* theFutureIsNow() {
    const dataA = yield nfcall(fs.readFile, "a.txt");
    const dataB = yield nfcall(fs.readFile, "b.txt");
    const dataC = yield nfcall(fs.readFile, "c,txt");
    yield ptimeout(60 * 1000);
    yield nfcall(fs.writeFile, "d.txt", dataA + dataB + dataC);
  }

  grun(theFutureIsNow); //실행
  ```

#### Promise.all

> Promise에는 all 메서드가 있다. <br>이 메서드는 배열로 받은 프로미스가 모두 완료될 떄 완료되며, 가능하다면 비동기적 코드를 동시에 실행한다.

- ```js
  //theFutureIsNow 함수가 Promise.all을 사용하도록 수정하기만 하면된다.
  function* theFutureIsNow() {
    const data = yield Promise.all([nfcall(fs.readFile, "a.txt"), nfcall(fs.readFile, "b.txt"), nfcall(fs.readFile, "c.txt")]);
    yield ptimeout(60 * 1000);
    yield nfcall(fs.writeFile, "d.txt", data[0] + data[1] + data[2]);
  }
  ```

#### 제너레이터 실행기와 예외 처리

> 제너레이터 실행기를 쓰면 try/catch를 써서 예외처리를 할수있다.

- 콜백이나 프라미스를 사용하면 예외 처리가 쉽지 않다.
  - 콜백에서 일으킨 예외는 그 콜백 밖에서 캐치할 수 없다.
- 제너레이터 실행기는 비동기적으로 실행하면서도 동기적인 동작 방식을 유지하므로 try/catch 문과 함꼐 쓸수 있다.
